---
keys:
  release: BaculaSystems-Public-Signature-08-2017.asc
  beta: BaculaSystems-Public-Signature-08-2017.asc
  nightly: nightly-misc/BaculaSystems-Nightly-Signature.asc

# This is the dictionary to add any additional package that
# need to be installed before BEE is installed
# The following entries are an example of the structure and
# they cannot be removed. They can be modified though.
# Valid operator values are: eq, le, lt, ge, gt

bee_additional_packages:
  debian:
    - apt-transport-https
    - sudo
    - openssl
    - ca-certificates
    - gnupg
    - acl
    - lsb-release
  ubuntu:
    - apt-transport-https
    - sudo
    - acl
    - gnupg
    - lsb-release
# package required by ansible deb822_repository module
    - python3-debian
