---
keys:
  - packages: bee
    packages_signatures:
      - BaculaSystems-Public-Signature-08-2017.asc
  - packages: community
    packages_signatures:
      - None

bee_additional_packages:
  debian:
    - apt-transport-https
    - sudo
    - openssl
    - ca-certificates
    - gnupg
    - acl
    - lsb-release
  ubuntu:
    - apt-transport-https
    - sudo
    - acl
    - lsb-release
    - gnupg
    - python3-debian
