---
- include_tasks: rpm-key_install_bee_keys.yml
- include_tasks: yum-repository_add_repo_file.yml
- include_tasks: yum_install_bee_fdonly.yml
- include_tasks: systemd_start_fd.yml
- include_tasks: All-platforms_config_fdonly.yml
- include_tasks: systemd_config_firewalld.yml 
- include_tasks: systemd_restart_fd.yml
- include_tasks: All-platforms_config_fdonly_dir.yml
- include_tasks: list_packages_build.yml
- name: Install gdb
  include_tasks: yum_install_gdb.yml
  when: install_gdb
