---
# This task list will install the latest Bacula Enterprise version
# available in the repository files added
# This will allow the upgrade of existent BEE install by
# adding the new repo file and using this same role to update
- name: install Bacula Enteprise Edition File Daemon
  apt:
    name: bacula-enterprise-client
    state: latest
  register: result
  environment:
    DEBIAN_FRONTEND: noninteractive
  retries: 3
  delay: 10
  failed_when:
    - result.stderr is defined
    - result.stderr | length > 0
    - "'debconf: delaying package configuration, since apt-utils is not installed' not in result.stderr"

- debug: msg="{{ result.stderr.split('\n') }}"
  when:
    - result.stderr is defined
    - result.stderr | length > 0
    - "'debconf: delaying package configuration, since apt-utils is not installed' not in result.stderr"
