- name: Gather the package facts
  ansible.builtin.package_facts:
    manager: auto

- name: get the list of bacula enterprise packages
  ansible.builtin.debug:
    msg: "{{ ansible_facts.packages['bacula-enterprise-client'] }}"
  when: "'bacula-enterprise-client' in ansible_facts.packages"
