---
- name: update packages, not upgrade service pack
  zypper:
    name: '*'
    state: latest
  retries: 3
  delay: 10
  failed_when:
    - result.stderr is defined
    - result.stderr | length > 0
