- name: download the oci-cli installation script
  get_url:
    url: https://raw.githubusercontent.com/oracle/oci-cli/master/scripts/install/install.sh
    dest: /tmp/install.sh
    mode: '0777'
  ignore_errors: true
- name: install the OCI CLI
  shell: /tmp/install.sh --install-dir /usr/local/lib/oracle-cli --exec-dir /usr/local/bin --script-dir /usr/local/bin --rc-file-path /root/.bashrc --accept-all-defaults
  async: 600
  poll: 30
  ignore_errors: true
- name: copy the RSA PKI pair to use with the oci cli
  copy:
    src: /root/.ansible/collections/ansible_collections/bacula/bacula_enterprise/roles/bee-sdplugin/files/{{ sdplugin }}/{{ item }}
    dest: /opt/bacula/etc/oci/
    owner: bacula
    group: bacula
    mode: '0600'
  with_items:
    - oci_api_key.pem
    - oci_api_key_public.pem
    - config
  ignore_errors: true
- name: test OCI CLI
  shell: /usr/local/bin/oci os object list -bn bucket-qa --cli-rc-file /opt/bacula/etc/oci/config --config-file /opt/bacula/etc/oci/config
  become: true
  become_user: bacula
  ignore_errors: true
  register: oci_object_list
- debug: msg="{{ oci_object_list.stdout.split('\n') }}"
  ignore_errors: true
- debug: msg="{{ oci_object_list.stderr.split('\n') }}"
  ignore_errors: true
