---
# dedup directories can be modified using --extra-vars='{"dedup_directories": [/mnt/dedup2/index, /mnt/dedup2/containers, /mnt/dedup2/volumes]}'
# the first directory for the dedup index, the second directory for the containers
- name: create dedup index and containers directories
  vars:
    dedup_directories:
      - index
      - containers
      - volumes
  file:
    path: "/opt/bacula/{{ sdplugin }}/{{ dedup_directories_item }}"
    state: directory
    owner: bacula
    group: bacula
    mode: "0755"
    recurse: true
  loop: "{{ dedup_directories }}"
  loop_control:
    loop_var: dedup_directories_item
