- name: Modify the Storage name, if defined
  ansible.builtin.replace:
    path: /opt/bacula/etc/bacula-sd.conf
    after: 'Storage {'
    regexp: "{{ storage_hostname.split('.')[0] }}-sd"
    replace: "{{ storage_name }}"
  when: storage_name is defined

- name: generate the autochanger resource definition to be included in the bacula-sd.conf file
  template:
    src: "{{ sdplugin }}_conf_in_bacula_sd.j2"
    dest: "/opt/bacula/etc/conf.d/storage/{{ storage_name }}-{{ sdplugin }}-autochanger-devices.conf"
    owner: bacula
    group: bacula
    mode: '0660'

- name: get the Storage Daemon password used to communicate with Director in the bacula-sd.conf file
  shell: "grep ^[[:space:]]*Password -m 1 /opt/bacula/etc/bacula-sd.conf | tr -d ' ' | tr -d '\"' | cut -d \"=\" -f2"
  register: current_sd_password

- name: set the dir_sd_password
  set_fact:
    dir_sd_password: "{{ current_sd_password.stdout }}"

- name: include director in the bacula-sd.conf file if director is a different host
  template:
    src: "director_conf_in_bacula_sd.j2"
    dest: "/opt/bacula/etc/conf.d/storage/{{ director_name }}.conf"
    owner: root
    group: bacula
    mode: '0660'
  when: director_hostname is defined and storage_hostname != director_hostname
