# dedup directoryes can be modified using --extra-vars='{"dedup_directories": [/mnt/dedup/index, /mnt/dedup/containers]}'
# the first directory for the dedup index, the second directory for the containers
- name: create dedup index and containers directories
  file:
    path: "{{ dedup_directories_item }}"
    state: directory
    owner: bacula
    group: disk
    mode: "0755"
    recurse: yes
  loop: "{{ dedup_directories }}"
  loop_control:
    loop_var: dedup_directories_item

- name: insert dedup index and containers directory configuration in the Storage Daemon configuration
  blockinfile:
    path: /opt/bacula/etc/bacula-sd.conf
    marker: "# {mark} Add DedupDirectory and DedupIndexDirectory"
    insertafter: "^Storage"
    block: |
      DedupDirectory = "{{ dedup_directories[1] }}"
      DedupIndexDirectory = "{{ dedup_directories[0] }}"
