# dedup directoryes can be modified using --extra-vars='{"dedup_directories": [/mnt/dedup/index, /mnt/dedup/containers]}'
# the first directory for the dedup index, the second directory for the containers
- name: create dedup index and containers directories
  vars:
    dedup_directories:
      - /opt/bacula/dedup/index
      - /opt/bacula/dedup/containers
  file:
    path: "{{ dedup_directories_item }}"
    state: directory
    owner: bacula
    group: bacula
    mode: "0755"
    recurse: yes
  loop: "{{ dedup_directories }}"
  loop_control:
    loop_var: dedup_directories_item
