---
# dedup directoryes can be modified using --extra-vars='{"dedup_directories": [/mnt/dedup/index, /mnt/dedup/containers, /mnt/dedup/volumes]}'
# the first directory for the dedup index, the second directory for the containers
- name: create dedup index and containers directories
  vars:
    dedup_directories:
      - index
      - containers
      - volumes
  file:
    path: "/opt/bacula/dedup/{{ dedup_directories_item }}"
    state: directory
    owner: bacula
    group: bacula
    mode: "0755"
    recurse: true
  loop: "{{ dedup_directories }}"
  loop_control:
    loop_var: dedup_directories_item

- name: insert dedup index and containers directory configuration in the Storage Daemon configuration
  blockinfile:
    path: /opt/bacula/etc/bacula-sd.conf
    marker: "# {mark} Add DedupDirectory and DedupIndexDirectory"
    insertafter: "^Storage"
    block: |
      DedupDirectory = /opt/bacula/dedup/containers
      DedupIndexDirectory = /opt/bacula/dedup/index
