- name: gather variables
  include_vars: "{{ repo_item }}"
  with_first_found:
  - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}-{{ansible_userspace_bits}}-repo.yml"
  loop_control:
    loop_var: repo_item

- name: get plugin variables
  set_fact:
    sdplugin_name: "{{ sdplugins_item.value.name }}"
    sdplugin_directory: "{{ sdplugins_item.value.directory }}"
    sdplugin_version: "{{ sdplugin_version | default(bee_version) }}"
  loop: "{{ sdplugins|dict2items }}"
  loop_control:
    loop_var: sdplugins_item
  when: sdplugins_item.key == sdplugin

- name: Add BEE DEB822 repository
  ansible.builtin.deb822_repository:
    name: "{{ repo_filename }}"
    types: deb
    suites: "{{ codename }}"
    uris: "{{ dl_area }}/debs/{{ sdplugin_directory }}/{{ sdplugin_version }}/{{ codename }}-{{ architecture }}"
    components: "{{ sdplugin_name }}"
    signed_by: "/etc/apt/trusted.gpg.d/{{ key_item.value }}"
  when: key_item.key == build
  loop: "{{ lookup('dict', keys) }}"
  loop_control:
    loop_var: key_item

# we do the cache update after adding the repository to get better the error
- name: update repositories cache
  apt:
    update_cache: yes
  register: apt_update_result
- debug:  msg="{{ apt_update_result.stdout.split('\n') }}"
  when: apt_update_result.stdout is defined
- debug:  msg="{{ apt_update_result.stderr.split('\n') }}"
  when: apt_update_result.stderr is defined
