- name: gather variables
  include_vars: "{{ repo_item }}"
  with_first_found:
  - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}-{{ansible_userspace_bits}}-repo.yml"
  loop_control:
    loop_var: repo_item
- name: get plugin variables
  set_fact:
    sdplugin_name: "{{ sdplugins_item.value.name }}"
    sdplugin_directory: "{{ sdplugins_item.value.directory }}"
  loop: "{{ sdplugins|dict2items }}"
  loop_control:
    loop_var: sdplugins_item
  when: sdplugins_item.key == sdplugin
- name: Add BEE APT repository
  apt_repository:
    repo: "deb {{ dl_area }}/debs/{{ sdplugin_directory }}/{{ bee_version }}/{{ codename }}-{{ architecture }}/ {{ codename }} {{ sdplugin_name }}"
    filename: "{{ repo_filename }}"
    codename: "{{ codename }}"
    state: present
    update_cache: no
# we do the cache update after adding the repository to get better the error
- name: update repositories cache
  apt:
    update_cache: yes
  register: apt_update_result
- debug:  msg="{{ apt_update_result.stdout.split('\n') }}"
  when: apt_update_result.stdout is defined
- debug:  msg="{{ apt_update_result.stderr.split('\n') }}"
  when: apt_update_result.stderr is defined
