---
- name: update repositories cache
  apt:
    update_cache: true
  register: apt_result
  retries: 3
  delay: 10
  failed_when:
    - result.stderr is defined
    - result.stderr | length > 0

- debug: msg="{{ apt_result.stdout.split('\n') }}"

- debug: msg="{{ apt_result.stderr.split('\n') }}"

- name: install additional packages
  apt:
    name: "{{ packages }}"
    state: latest
  retries: 3
  delay: 10
  failed_when:
    - result.stderr is defined
    - result.stderr | length > 0
  vars:
    packages:
      - apt-transport-https
      - sudo
