---
    - include: yum-repository_add_repo_file.yml
    - include: yum_install_bee_sdplugin.yml
    - include: "{{ file_item }}"
      loop_control:
        loop_var: file_item
      with_first_found:
        - files:
          - "All-platforms_config_{{ sdplugin }}_sd.yml"
          skip: true
    - include: All-platforms_config_sdplugin.yml
    - include: yum_list_packages_build.yml
    - include: systemd_restart_sd.yml
    - include: All-platforms_config_sdplugin_dir.yml
