---
- include_tasks: yum-repository_add_repo_file.yml
- include_tasks: yum_install_bee_sdplugin.yml
- include_tasks: "{{ file_item }}"
  loop_control:
    loop_var: file_item
  with_first_found:
    files:
      - "All-platforms_config_{{ sdplugin }}_sd.yml"
    skip: true
- include_tasks: All-platforms_config_sdplugin.yml
- include_tasks: yum_list_packages_build.yml
- include_tasks: service_restart_sd.yml
- include_tasks: All-platforms_config_sdplugin_dir.yml
