---
    - include: yum-repository_add_repo_file.yml
    - include: yum_install_bee_sdplugin.yml
    - include: "{{ item }}"
      with_first_found:
        - files:
          - "All-platforms_config_{{ sdplugin }}_sd.yml"
          skip: true
    - include: All-platforms_include_plugin_autochanger.yml
    - include: yum_list_packages_build.yml
    - include: service_restart_sd.yml
