---
    - include: apt-repository_add_repo_file.yml
    - include: apt_install_bee_sdplugin.yml
    - include: "{{ file_item }}"
      with_first_found:
        - files:
          - "All-platforms_config_{{ sdplugin }}_sd.yml"
          skip: true
      loop_control:
        loop_var: file_item
    - include: All-platforms_include_plugin_autochanger.yml
    - include: apt_list_packages_build.yml
    - include: systemd_restart_sd.yml
