---
- include_tasks: zypper-repository_add_repo_file.yml
- include_tasks: zypper_install_bee_sdplugin.yml
- include_tasks: "{{ item }}"
  vars:
    params:
      files:
        - "All-platforms_config_{{ sdplugin }}_sd.yml"
  loop: "{{ query('first_found', params, errors='ignore') }}"
- include_tasks: list_packages_build.yml
- include_tasks: All-platforms_config_sdplugin.yml
  when: sdplugin != 'sir'
- include_tasks: systemd_restart_sd.yml
- include_tasks: All-platforms_config_sdplugin_dir.yml
  when: sdplugin != 'sir'
