- name: gather variables
  include_vars: "{{ repo_item }}"
  with_first_found:
  - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}-{{ansible_userspace_bits}}-repo.yml"
  loop_control:
    loop_var: repo_item
- name: get plugin variables
  set_fact:
    sdplugin_name: "{{ sdplugins_item.value.name }}"
    sdplugin_directory: "{{ sdplugins_item.value.directory }}"
  loop: "{{ sdplugins|dict2items }}"
  loop_control:
    loop_var: sdplugins_item
  when: sdplugins_item.key == sdplugin
- name: Add BEE YUM repository
  yum_repository:
    name: "{{ repo_name }}"
    file: "{{ repo_filename }}"
    description: "{{ description }}"
    baseurl: "{{ dl_area }}/rpms/{{ sdplugin_directory }}/{{ bee_version }}/{{ rhel_version }}-{{ architecture }}/"
    enabled: "{{ enabled }}"
    protect: "{{ protect }}"
    gpgcheck: "{{ gpgcheck }}"
