---
---# This task list will install the latest Bacula Enterprise version
# available in the repository files added
# This will allow the upgrade of existent BEE install by
# adding the new repo file and using this same role to update
- name: get plugin variables
  set_fact:
    sdplugin_package_name: "{{ sdplugins_item.value.package_name}}"
  loop: "{{ sdplugins|dict2items }}"
  loop_control:
    loop_var: sdplugins_item
  when: sdplugins_item.key == sdplugin
- name: install Bacula Enteprise Edition plugin for Storage Daemon
  yum:
    name: "{{ sdplugin_package_name }}"
    state: latest
  register: result
- debug: msg="{{ result.stderr.split('\n') }}"
  when: result.stderr is defined
