- name: get the list of bacula enterprise packages
  shell: "zypper packages --installed-only | grep {{ sdplugin_package_name }}"
  register: rpm_packages
- name: list bacula enterprise packages builds
  debug:
    msg: "{{ rpm_packages.stdout_lines }}"
