- name: gather Plugin dependencies repository 
  set_fact: add_repo_dependency="{{ item.1.package_dependency_name }}"
  with_subelements:
    - "{{sdplugins_dependencies}}"
    - dependencies
  when:
    - "((sdplugin is defined and item.0.plugin_name == sdplugin) or (fdplugin is defined and item.0.plugin_name == fdplugin))"
    - "bee_version is version(item.1.bee_version, item.1.operator) and item.1.os_distribution == ansible_distribution"
    -  "item.1.os_distribution_major_version == ansible_distribution_major_version|int and item.1.add_repo == true" 
- name: add Plugin dependencies repository and key if required
  include: "{{ ansible_distribution }}_add_{{ add_repo_dependency }}_repo.yml"
  when: add_repo_dependency is defined
- name: install Bacula Enteprise plugin for Storage Daemon dependencies
  yum:
    name: "{{ item.1.package_dependency_name }}"
    state: latest
  with_subelements:
    - "{{sdplugins_dependencies}}"
    - dependencies
  when:
    - "((sdplugin is defined and item.0.plugin_name == sdplugin) or (fdplugin is defined and item.0.plugin_name == fdplugin))"
    - "bee_version is version(item.1.bee_version, item.1.operator) and item.1.os_distribution == ansible_distribution"
    - "item.1.os_distribution_major_version == ansible_distribution_major_version|int"
