---
- name: Register the Microsoft RedHat repository
  get_url:
    url: "https://packages.microsoft.com/config/rhel/{{ ansible_distribution_major_version }}/prod.repo"
    dest: /etc/yum.repos.d/microsoft.repo
    owner: root
    group: root
    mode: '0644'

- name: Install PowerShell
  yum:
    name: powershell
    state: latest

- name: Start PowerShell and Install PnP.Powershell
  shell: Install-Module -Name 'PnP.PowerShell' -Force | ConvertTo-Json
  args:
    executable: /usr/bin/pwsh
  register: PnP_powershell_status

- debug: "{{ PnP_powershell_status.stdout.split('\n') }}"
- debug: "{{ PnP_powershell_status.stderr.split('\n') }}"
