---
- name: Include Bacula Enterprise Plugin Dependencies Installation file
  include: "{{ item }}"
  vars:
    params:
      files:
        - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}-{{ansible_userspace_bits}}_install_plugin_dependencies.yml"
        - "{{ ansible_distribution }}-{{ ansible_distribution_version }}-{{ansible_userspace_bits}}_install_plugin_dependencies.yml"
  loop: "{{ query('first_found', params) }}"
