- name: add azure-cli repo
  community.general.zypper_repository:
    name: azure-cli
    repo: 'https://packages.microsoft.com/yumrepos/azure-cli'
    description: 'Azure CLI'
    state: present

- name: install Azure CLI
  community.general.zypper:
    name: azure-cli
    state: present
    update_cache: yes
    force_resolution: yes
