- name: install Bacula Enteprise plugin for Storage Daemon dependencies if required
  block:

    - name: Install the GPG Public Key if needed
      rpm_key:
        state: present
        key: "{{ item.gpgkey }}"
      register: result
      retries: 3
      delay: 10
      until: result.status == 200
      failed_when: result.status != 200
      when:
        - item.install_gpgkey|default(false)|bool == true 

    - name: add Plugin dependencies repository and key if required
      include_tasks: add_repo_dependency.yml
      vars:
        add_repo_dependency: "{{ item.package_name }}"
      when:
        - "item.add_repo == true"

    - name: set the plugin_dependency value as the dependency name
      set_fact:
        plugin_dependency="{{ item.package_name }}"

    - name: Install {{ plugin_dependency }} using package manager
      yum:
        name: "{{ item.package_dependency_name}}"
        state: latest
      when:
        - item.use_package_manager|default(false)|bool == true

    - name: Install {{ plugin_dependency }} not using package manager
      include_tasks: install_plugin_dependencies.yml
      vars:
        plugin_dependency: "{{ item.package_name }}"
      when:
        - item.use_package_manager|default(false)|bool == false

    - name: check dependency is correctly installed
      include_tasks: "{{ lookup('ansible.builtin.first_found', params) }}"
      when:
        - item.check_dependency_install|default(false)|bool == true
      vars:
        params:
          files:
            - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}-{{ansible_userspace_bits}}_check_{{ plugin_dependency }}.yml"
            - "{{ ansible_distribution }}-{{ ansible_distribution_version }}-{{ansible_userspace_bits}}_check_{{ plugin_dependency }}.yml"
            - "{{ ansible_distribution }}_check_{{ plugin_dependency }}.yml"
            - "check_{{ plugin_dependency }}.yml"
          skip: true
