---
    - include: apt_update_package_manager.yml
    - include: apt_install_additional_packages.yml
    - include: apt-key_install_bee_keys.yml
    - include: apt-repository_add_repo_file.yml
    - include: apt_update_and_upgrade_packages.yml
    - include: apt_install_postgresql.yml
    - include: apt_install_bee.yml
    - include: apt_list_packages_build.yml
    - include: All-platforms_include_all_configs.yml
    - include: service_restart_sd.yml
    - include: service_disable_stop_Director.yml
