---
- name: gather variables
  include_vars: "{{ repo_item }}"
  with_first_found:
  - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}-{{ ansible_userspace_bits }}-repo.yml"
  loop_control:
    loop_var: repo_item

- name: get plugin variables
  set_fact:
    fdplugin_name: "{{ fdplugins_item.value.name }}"
    fdplugin_directory: "{{ fdplugins_item.value.directory }}"
    fdplugin_component: "main"
  loop: "{{ fdplugins|dict2items }}"
  loop_control:
    loop_var: fdplugins_item
  when:
    - fdplugins_item.key == fdplugin
    - fdplugins_item.value.directory == "bin"

- name: get plugin variables
  set_fact:
    fdplugin_name: "{{ fdplugins_item.value.name }}"
    fdplugin_directory: "{{ fdplugins_item.value.directory }}"
    fdplugin_component: "{{ fdplugins_item.value.name }}"
  loop: "{{ fdplugins|dict2items }}"
  loop_control:
    loop_var: fdplugins_item
  when:
    - fdplugins_item.key == fdplugin
    - fdplugins_item.value.directory != "bin"

- name: Add BEE release DEB822 repository
  ansible.builtin.deb822_repository:
    name: "{{ repo_filename }}"
    types: deb
    suites: "{{ codename }}"
    uris: "{{ dl_area }}/debs/{{ fdplugin_directory }}/{{ bee_version }}/{{ codename }}-{{ architecture }}"
    components: "{{ fdplugin_component }}"
    signed_by: "/etc/apt/trusted.gpg.d/{{ key_item.value }}"
  when: 
    - key_item.key == build
    - build == "release"
  loop: "{{ keys|dict2items }}"
  loop_control:
    loop_var: key_item

- name: Add BEE beta DEB822 repository
  ansible.builtin.deb822_repository:
    name: "{{ repo_filename }}"
    types: deb
    suites: "{{ codename }}"
    uris: "{{ dl_area }}/beta-debs/{{ fdplugin_directory }}/{{ bee_version }}/{{ codename }}-{{ architecture }}"
    components: "{{ fdplugin_component }}"
    signed_by: "/etc/apt/trusted.gpg.d/{{ key_item.value }}"
  when: 
    - key_item.key == build
    - build == "beta"
  loop: "{{ keys|dict2items }}"
  loop_control:
    loop_var: key_item

- name: Add BEE nightly DEB822 repository
  ansible.builtin.deb822_repository:
    name: "{{ repo_filename }}"
    types: deb
    suites: "{{ codename }}"
    uris: "{{ dl_area }}/nightly-debs/{{ fdplugin_directory }}/{{ bee_version }}/{{ codename }}-{{ architecture }}"
    components: "{{ fdplugin_component }}"
    signed_by: "/etc/apt/trusted.gpg.d/{{ key_item.value }}"
  when: 
    - key_item.key == build
    - build == "nightly"
  loop: "{{ keys|dict2items }}"
  loop_control:
    loop_var: key_item

# we do the cache update after adding the repository to get better the error
- name: update repositories cache
  apt:
    update_cache: true
  register: apt_update_result
- debug: msg="{{ apt_update_result.stdout.split('\n') }}"
  when: apt_update_result.stdout is defined
- debug: msg="{{ apt_update_result.stderr.split('\n') }}"
  when: apt_update_result.stderr is defined
