- name: gather variables
  include_vars: "{{ repo_item }}"
  with_first_found:
  - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}-{{ ansible_userspace_bits }}-repo.yml"
  loop_control:
    loop_var: repo_item
- name: get plugin variables
  set_fact:
    fdplugin_name: "{{ fdplugins_item.value.name }}"
    fdplugin_directory: "{{ fdplugins_item.value.directory }}"
  loop: "{{ fdplugins|dict2items }}"
  loop_control:
    loop_var: fdplugins_item
  when: fdplugins_item.key == fdplugin
- name: Add BEE APT repository
  apt_repository:
    repo: "deb {{ dl_area }}/debs/{{ fdplugin_directory }}/{{ bee_version }}/{{ codename}}-{{ architecture }}/ {{ codename }} {{ fdplugin_name }}"
    filename: "{{ repo_filename }}"
    codename: "{{ codename }}"
    state: present
    update_cache: false
# we do the cache update after adding the repository to get better the error
- name: update repositories cache
  apt:
    update_cache: true
  register: apt_update_result
- debug:  msg="{{ apt_update_result.stdout.split('\n') }}"
  when: apt_update_result.stdout is defined
- debug:  msg="{{ apt_update_result.stderr.split('\n') }}"
  when: apt_update_result.stderr is defined
