---
# This task list will install the latest Bacula Enterprise version
# available in the repository files added
# This will allow the upgrade of existent BEE install by
# adding the new repo file and using this same role to update
- name: get plugin variables
  set_fact:
    fdplugin_package_name: "{{ fdplugins_item.value.package_name}}"
  loop: "{{ fdplugins|dict2items }}"
  loop_control:
    loop_var: fdplugins_item
  when: fdplugins_item.key == fdplugin

- name: install Bacula Enteprise plugin for File Daemon
  apt:
    name: "{{ fdplugin_package_name }}"
    state: latest
  register: result

- debug: msg="{{ result.stderr.split('\n') }}"
  when: result.stderr is defined
