---
- name: disable SELinux
  selinux:
    state: disabled
<<<<<<< HEAD
  register: selinux_status
=======
  register: selinux_status 
>>>>>>> 19f376f... added Debian 11 to bweb role
  ignore_errors: true
- debug: msg="{{ selinux_status.msg }}"
- name: reboot the vm if required
  reboot:
  when: selinux_status.reboot_required
  register: reboot_status
