- name: disable SELinux
  selinux:
    state: disabled
  register: selinux_status 
  ignore_errors: yes
- debug: msg="{{ selinux_status.msg }}"
- name: reboot the vm if required
  reboot: 
  when: selinux_status.reboot_required
  register: reboot_status
