---
- include: yum-repository_add_repo_file.yml
- include: yum_install_bee_fdplugin.yml
- include: systemd_start_fd.yml
- include: "{{ fdplugin_config_file }}"
  with_first_found:
    - files:
      - "{{ fdplugin }}_config_fdplugin.yml"
    skip: true
  loop_control:
    loop_var: fdplugin_config_file
- include: systemd_restart_fd.yml
- include: yum_list_packages_build.yml
- include: All-platforms_config_fdplugin_dir.yml
