---
- include_tasks: zypper-repository_add_repo_file.yml
- include_tasks: zypper_install_bee_fdplugin.yml
- include_tasks: systemd_start_fd.yml
- include_tasks: "{{ fdplugin_config_file }}"
  with_first_found:
    - files:
        - "{{ fdplugin }}_config_fdplugin.yml"
      skip: true
  loop_control:
    loop_var: fdplugin_config_file
- include_tasks: systemd_restart_fd.yml
- include_tasks: All-platforms_config_fdplugin_dir.yml
- include_tasks: list_packages_build.yml
