---
- name: gather variables
  include_vars: "{{ repo_item }}"
  with_first_found:
  - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}-{{ansible_userspace_bits}}-repo.yml"
  loop_control:
    loop_var: repo_item
- name: get plugin variables
  set_fact:
    fdplugin_name: "{{ fdplugins_item.value.name }}"
    fdplugin_directory: "{{ fdplugins_item.value.directory }}"
  loop: "{{ fdplugins|dict2items }}"
  loop_control:
    loop_var: fdplugins_item
  when: fdplugins_item.key == fdplugin
- name: Add BEE release YUM repository
  yum_repository:
    name: "{{ repo_name }}"
    file: "{{ repo_filename }}"
    description: "{{ description }}"
    baseurl: "{{ dl_area }}/rpms/{{ fdplugin_directory }}/{{ bee_version }}/{{ rhel_version }}-{{ architecture }}/"
    enabled: "{{ enabled }}"
    protect: "{{ protect }}"
    gpgcheck: "{{ gpgcheck }}"
