---
- name: get plugin package name
  set_fact:
    fdplugin_package_name: "{{ fdplugins_item.value.package_name}}"
  loop: "{{ fdplugins|dict2items }}"
  loop_control:
    loop_var: fdplugins_item
  when: fdplugins_item.key == fdplugin
- name: get list of plugin packages installed
  yum:
    list=installed
  register: yum_packages
- name: list bacula enterprise packages builds
  debug:
    msg: "{{ yum_packages | json_query(query_packages) }}"
  vars:
    query_packages: "results[?name == '{{ fdplugin_package_name }}']"
