---
- name: include repository dependencies dictionary
  include_vars: bweb_dependencies.yml

- name: add BWeb dependencies repository and key if required
  include_tasks: add_repo_dependency.yml
  vars:
    add_repo_dependency: "{{ dependency_item.value.dependency_name }}"
  loop: "{{ lookup('dict', bweb_dependencies) }}"
  loop_control:
    loop_var: dependency_item
  when:
    - "bee_version is version(dependency_item.value.bee_version, dependency_item.value.operator) and dependency_item.value.os_distribution == ansible_distribution"
    - "dependency_item.value.os_distribution_major_version == ansible_distribution_major_version|int and dependency_item.value.add_repo == true"
    - "dependency_item.value.use_package_manager == true"

- name: install BWeb packages dependencies
  apt:
    name: "{{ dependency_item.value.package_dependency_name}}"
    state: latest
  loop: "{{ lookup('dict', bweb_dependencies) }}"
  loop_control:
    loop_var: dependency_item
  when:
    - "bee_version is version(dependency_item.value.bee_version, dependency_item.value.operator) and dependency_item.value.os_distribution == ansible_distribution"
    - "dependency_item.value.os_distribution_major_version == ansible_distribution_major_version|int"
    - "dependency_item.value.use_package_manager == true"
