---
    - include_tasks: yum-repository_add_repo_file.yml 
    - include_tasks: yum_install_bweb.yml
    - include_tasks: systemd_start_bweb.yml
    - include_tasks: systemd_config_firewalld.yml
    - include_tasks: yum_list_packages_build.yml
    - include_tasks: check_connection.yml
