---
    - name: Include BWeb Management Suite Installation file
      include: "{{ item }}"
      vars:
        params:
          files:
            - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}-{{ansible_userspace_bits}}_install_bweb.yml"
            - "{{ ansible_distribution }}-{{ ansible_distribution_version }}-{{ansible_userspace_bits}}_install_bweb.yml"
      loop: "{{ query('first_found', params) }}"
