---
- name: gather variables
  include_vars: "{{ repo_item }}"
  with_first_found:
  - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}{{ ansible_distribution_release}}-{{ansible_userspace_bits}}-bweb-repo.yml"
  loop_control:
    loop_var: repo_item
- name: Add BEE nightly ZYPPER repository
  zypper_repository:
    name: "{{ repo_filename }}"
    description: "{{ description }}"
    repo: "{{ dl_area }}/nightly-rpms/bweb/{{ bee_version }}/{{ sles_version }}-{{ architecture }}/"
    auto_import_keys: "{{ auto_import_keys }}"
  when: build == "nightly"
- name: Add BEE beta ZYPPER repository
  zypper_repository:
    name: "{{ repo_filename }}"
    description: "{{ description }}"
    repo: "{{ dl_area }}/beta-rpms/bweb/{{ bee_version }}/{{ sles_version }}-{{ architecture }}/"
    auto_import_keys: "{{ auto_import_keys }}"
  when: build == "beta"
- name: Add BEE release ZYPPER repository
  zypper_repository:
    name: "{{ repo_filename }}"
    description: "{{ description }}"
    repo: "{{ dl_area }}/rpms/bweb/{{ bee_version }}/{{ sles_version }}-{{ architecture }}/"
    auto_import_keys: "{{ auto_import_keys }}"
  when: build == "release"
# dag repository
- name: gather variables
  include_vars: "{{ repo_item }}"
  with_first_found:
  - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}{{ ansible_distribution_release}}-{{ansible_userspace_bits}}-dag-repo.yml"
  loop_control:
    loop_var: repo_item
- name: Add Bacula Systems dag repository for SLES hosts
  zypper_repository:
    name: "{{ repo_filename }}"
    description: "{{ description }}"
    repo: "https://www.baculasystems.com/dl/DAG/{{ sles_version }}-{{ architecture }}/"
    auto_import_keys: "{{ auto_import_keys }}"
    disable_gpg_check: "{{ disable_gpg_check }}"
