- name: Gather the package facts
  ansible.builtin.package_facts:
    manager: auto

- name: get the list of bacula enterprise packages
  ansible.builtin.debug:
    msg: "{{ ansible_facts.packages['bacula-enterprise-postgresql'] }}"
  when: "'bacula-enterprise-postgresql' in ansible_facts.packages"

- name: get the list of bacula enterprise BWeb packages
  ansible.builtin.debug:
    msg: "{{ ansible_facts.packages['bacula-enterprise-bweb'] }}"
  when: "'bacula-enterprise-bweb' in ansible_facts.packages"
