# This task list will install the latest Bacula Enterprise version
# available in the repository files added
# This will allow the upgrade of existent BEE install by
# adding the new repo file and using this same role to update
- name: get plugin variables
  set_fact:
    dirplugin_package_name: "{{ dirplugins_item.value.package_name}}"
  loop: "{{ dirplugins|dict2items }}"
  loop_control:
    loop_var: dirplugins_item
  when: dirplugins_item.key == dirplugin
- name: install Bacula Enteprise plugin for File Daemon
  yum:
    name: "{{ dirplugin_package_name }}"
    state: latest
  register: result
- debug: msg="{{ result.stderr.split('\n') }}"
  when: result.stderr is defined
