---
- name: install package signatures for Debian/Ubuntu
  ansible.builtin.get_url:
    url: "{{ dl_area }}/{{ key_item.1 }}"
    dest: /etc/apt/trusted.gpg.d/
  register: result
  retries: 3
  delay: 10
  until:
    - result.status_code == 200
  failed_when:
    - result.status_code != 200
  when: key_item[0].packages == 'bee'
  loop: "{{ keys|subelements('packages_signatures') }}"
  loop_control:
    loop_var: key_item
