---
- name: install package signatures for Debian/Ubuntu
  ansible.builtin.get_url:
    url: "{{ dl_area }}/{{ key_item.value }}"
    dest: "/etc/apt/trusted.gpg.d/{{ key_item.value }}"
  register: result
  retries: 3
  delay: 10
  until: result.status_code == 200 or result.status_code == 304
  failed_when:
    - result.status_code != 200
    - result.status_code != 304
  when: key_item.key == build
  loop: "{{ lookup('dict', keys) }}"
  loop_control:
    loop_var: key_item

#- debug: msg="{{ result.results.key_item.dest }}"

#- name: get the Bacula Systems public signature path and filename downloaded
#  ansible.builtin.set_fact:
#    keyring_file: "{{ result.dest }}"
