- name: update repositories cache
  apt:
    update_cache: yes

- name: install additional packages for Debian/Ubuntu
  apt:
    name: "{{ bee_additional_packages[ansible_distribution|lower] }}"
    state: latest
    force: yes
