---
- include_tasks: yum_upgrade_packages.yml
- include_tasks: rpm-key_install_bee_keys.yml
- include_tasks: yum-repository_add_repo_file.yml
- include_tasks: yum_install_postgresql.yml
- include_tasks: systemd_initialize_and_enable_postgresql.yml
- include_tasks: yum_install_bee.yml
- include_tasks: list_packages_build.yml
- include_tasks: systemd_start_postgresql.yml
- include_tasks: All-platforms_create_bacula_database.yml
- include_tasks: All-platforms_config_dir.yml
- include_tasks: All-platforms_config_sd.yml
- include_tasks: systemd_start_bee_services.yml
- include_tasks: All-platforms_BEE_check_director_status.yml
- include_tasks: All-platforms_BEE_check_FD_status.yml
- include_tasks: All-platforms_BEE_check_SD_status.yml
- include_tasks: systemd_config_firewalld.yml
- include_tasks: All-platforms_PostgreSQL_version.yml
- name: Install gdb
  include_tasks: yum_install_gdb.yml
  when: install_gdb
