---
- name: Add BEE package signatures for CentOS/RedHat/SLES
  rpm_key:
    key: "{{ dl_area }}/{{ key_item.1 }}"
    state: present
  register: result
  retries: 3
  delay: 10
  until: result.status == 200
  failed_when: result.status != 200
  when: key_item[0].packages == 'bee'
  loop: "{{ keys|subelements('packages_signatures') }}"
  loop_control:
    loop_var: key_item
