---
- name: Enable SUSE Package Hub respository
  remote_user: root
  shell: "SUSEConnect -p PackageHub/{{ ansible_distribution_major_version }}.{{ ansible_distribution_release }}/x86_64"
  register: enable_packagehub_result
  delegate_to: "{{ director_hostname }}.supportlab.lan"
- debug:  msg="{{ enable_packagehub_result.stdout.split('\n') }}"
  delegate_to: "{{ director_hostname }}.supportlab.lan"
- debug:  msg="{{ enable_packagehub_result.stderr.split('\n') }}"
  delegate_to: "{{ director_hostname }}.supportlab.lan"
