---
- name: Enable SUSE Package Hub respository
  remote_user: root
  shell: "SUSEConnect -p PackageHub/15.4/x86_64"
  register: enable_packagehub_result
  delegate_to: "{{ vm_name }}.supportlab.lan"
- debug:  msg="{{ enable_packagehub_result.stdout.split('\n') }}"
  delegate_to: "{{ vm_name }}.supportlab.lan"
- debug:  msg="{{ enable_packagehub_result.stderr.split('\n') }}"
  delegate_to: "{{ vm_name }}.supportlab.lan"
