---
- include_tasks: apt_update_package_manager.yml
- include_tasks: apt_install_additional_packages.yml
- include_tasks: deb_install_bee_keys.yml
- include_tasks: apt-repository_add_repo_file.yml
- include_tasks: apt_update_and_upgrade_packages.yml
- include_tasks: apt_install_postgresql.yml
- include_tasks: apt_install_bee.yml
- include_tasks: list_packages_build.yml
- include_tasks: All-platforms_config_dir.yml
- include_tasks: All-platforms_config_sd.yml
- include_tasks: service_start_bee_services.yml
- include_tasks: All-platforms_BEE_check_director_status.yml
- include_tasks: All-platforms_BEE_check_FD_status.yml
- include_tasks: All-platforms_BEE_check_SD_status.yml
- include_tasks: All-platforms_BEE_check_catalog_version.yml
- include_tasks: All-platforms_PostgreSQL_version.yml
- name: Install gdb
  include_tasks: apt_install_gdb.yml
  when: install_gdb
