- name: install gdb
  yum:
    name: gdb
    state: latest
  register: result
  retries: 3
  delay: 10
  failed_when:
    - result.stderr is defined
    - result.stderr | length > 0

- debug: msg="{{ result.stderr.split('\n') }}"
  when: result.stderr is defined
